#
# (C) Copyright IBM Corp. 2001
#
#
# $Id: Makefile,v 1.6 2003/08/13 21:20:53 dgrove-oss Exp $
#
# @author Julian Dolby
#
include		$(RVM_BUILD)/Make.rules.target

JCOMPILE=$(RVM_BUILD)/jbuild.tool

default:;

clean:
	$(RM) *.class
