#
# (C) Copyright IBM Corp. 2002
#
#$Id: Makefile,v 1.3 2002/11/02 23:38:52 dgrove-oss Exp $
#
# @author David Grove

COMMON_DIR = $(RVM_ROOT)/rvm/src/vm/compilers/optimizing/ir/conversions/lir2mir
#
RULE_FILES = $(MIR_LIR2MIR_DIR)/IA32.rules 
